"""
BV-BRC Data Functions

This module provides wrapper functions for the BV-BRC Solr API, exposing
genome, genome feature, and antibiotics querying capabilities through a simplified interface.
"""

# Import common functions
from .common_functions import (
    create_bvbrc_client,
    query_direct,
    format_query_result
)

# Import genome functions
from .genome_functions import (
    query_genome_by_id,
    query_genome_by_taxon_id,
    query_genome_by_genome_name,
    query_genome_by_species,
    query_genome_by_genus,
    query_genome_by_filters
)

# Import genome feature functions
from .genome_feature_functions import (
    query_genome_feature_by_id,
    query_genome_feature_by_genome_id,
    query_genome_feature_by_gene,
    query_genome_feature_by_product,
    query_genome_feature_by_filters
)

# Import antibiotics functions
from .antibiotics_functions import (
    query_antibiotics_by_pubchem_cid,
    query_antibiotics_by_filters,
    query_antibiotics_by_keyword,
    query_antibiotics_by_name,
    query_antibiotics_by_cas_id,
    query_antibiotics_by_molecular_formula,
    query_antibiotics_by_atc_classification,
    query_antibiotics_by_mechanism_of_action,
    query_antibiotics_by_pharmacological_class,
    query_antibiotics_by_synonym,
    query_antibiotics_by_molecular_weight_range,
    query_antibiotics_by_date_range,
    query_antibiotics_all
)

# Import bioset_result functions
from .bioset_result_functions import (
    query_bioset_result_by_id,
    query_bioset_result_by_filters,
    query_bioset_result_by_bioset_id,
    query_bioset_result_by_bioset_name,
    query_bioset_result_by_bioset_description,
    query_bioset_result_by_bioset_type,
    query_bioset_result_by_entity_id,
    query_bioset_result_by_entity_name,
    query_bioset_result_by_entity_type,
    query_bioset_result_by_exp_id,
    query_bioset_result_by_exp_name,
    query_bioset_result_by_exp_title,
    query_bioset_result_by_exp_type,
    query_bioset_result_by_feature_id,
    query_bioset_result_by_gene,
    query_bioset_result_by_gene_id,
    query_bioset_result_by_genome_id,
    query_bioset_result_by_locus_tag,
    query_bioset_result_by_organism,
    query_bioset_result_by_patric_id,
    query_bioset_result_by_product,
    query_bioset_result_by_protein_id,
    query_bioset_result_by_result_type,
    query_bioset_result_by_strain,
    query_bioset_result_by_taxon_id,
    query_bioset_result_by_uniprot_id,
    query_bioset_result_by_other_id,
    query_bioset_result_by_treatment_name,
    query_bioset_result_by_treatment_type,
    query_bioset_result_by_treatment_amount,
    query_bioset_result_by_treatment_duration,
    query_bioset_result_by_counts_range,
    query_bioset_result_by_fpkm_range,
    query_bioset_result_by_log2_fc_range,
    query_bioset_result_by_p_value_range,
    query_bioset_result_by_tpm_range,
    query_bioset_result_by_other_value_range,
    query_bioset_result_by_z_score_range,
    query_bioset_result_by_version,
    query_bioset_result_by_date_inserted_range,
    query_bioset_result_by_date_modified_range,
    query_bioset_result_by_keyword,
    query_bioset_result_all,
)

# Import bioset functions
from .bioset_functions import (
    query_bioset_by_id,
    query_bioset_by_filters,
    query_bioset_by_name,
    query_bioset_by_type,
    query_bioset_by_exp_id,
    query_bioset_by_exp_name,
    query_bioset_by_exp_type,
    query_bioset_by_organism,
    query_bioset_by_strain,
    query_bioset_by_taxon_id,
    query_bioset_by_entity_type,
    query_bioset_by_result_type,
    query_bioset_by_analysis_method,
    query_bioset_by_analysis_group_1,
    query_bioset_by_analysis_group_2,
    query_bioset_by_treatment_type,
    query_bioset_by_treatment_name,
    query_bioset_by_study_name,
    query_bioset_by_study_pi,
    query_bioset_by_study_institution,
    query_bioset_by_genome_id,
    query_bioset_by_date_range,
    query_bioset_by_modified_date_range,
    query_bioset_by_keyword,
    query_bioset_all
)

# Import enzyme class reference functions
from .enzyme_class_ref_functions import (
    query_enzyme_class_ref_by_ec_number,
    query_enzyme_class_ref_by_filters,
    query_enzyme_class_ref_by_ec_description,
    query_enzyme_class_ref_by_go_term,
    query_enzyme_class_ref_by_version,
    query_enzyme_class_ref_by_date_inserted_range,
    query_enzyme_class_ref_by_date_modified_range,
    query_enzyme_class_ref_by_keyword,
    query_enzyme_class_ref_all
)

# Import epitope assay functions
from .epitope_assay_functions import (
    query_epitope_assay_by_id,
    query_epitope_assay_by_filters,
    query_epitope_assay_by_assay_group,
    query_epitope_assay_by_assay_measurement,
    query_epitope_assay_by_assay_measurement_unit,
    query_epitope_assay_by_assay_method,
    query_epitope_assay_by_assay_result,
    query_epitope_assay_by_assay_type,
    query_epitope_assay_by_authors,
    query_epitope_assay_by_epitope_id,
    query_epitope_assay_by_epitope_sequence,
    query_epitope_assay_by_epitope_type,
    query_epitope_assay_by_host_name,
    query_epitope_assay_by_host_taxon_id,
    query_epitope_assay_by_mhc_allele,
    query_epitope_assay_by_mhc_allele_class,
    query_epitope_assay_by_organism,
    query_epitope_assay_by_pdb_id,
    query_epitope_assay_by_pmid,
    query_epitope_assay_by_protein_accession,
    query_epitope_assay_by_protein_id,
    query_epitope_assay_by_protein_name,
    query_epitope_assay_by_start,
    query_epitope_assay_by_end,
    query_epitope_assay_by_taxon_id,
    query_epitope_assay_by_taxon_lineage_id,
    query_epitope_assay_by_taxon_lineage_name,
    query_epitope_assay_by_title,
    query_epitope_assay_by_position_range,
    query_epitope_assay_by_date_inserted_range,
    query_epitope_assay_by_date_modified_range,
    query_epitope_assay_by_keyword,
    query_epitope_assay_all
)

# Import epitope functions
from .epitope_functions import (
    query_epitope_by_id,
    query_epitope_by_filters,
    query_epitope_by_epitope_sequence,
    query_epitope_by_epitope_type,
    query_epitope_by_host_name,
    query_epitope_by_organism,
    query_epitope_by_protein_accession,
    query_epitope_by_protein_id,
    query_epitope_by_protein_name,
    query_epitope_by_start,
    query_epitope_by_end,
    query_epitope_by_taxon_id,
    query_epitope_by_bcell_assays,
    query_epitope_by_mhc_assays,
    query_epitope_by_tcell_assays,
    query_epitope_by_total_assays,
    query_epitope_by_comment,
    query_epitope_by_assay_result,
    query_epitope_by_taxon_lineage_id,
    query_epitope_by_taxon_lineage_name,
    query_epitope_by_position_range,
    query_epitope_by_total_assays_range,
    query_epitope_by_date_inserted_range,
    query_epitope_by_date_modified_range,
    query_epitope_by_keyword,
    query_epitope_all
)

# Import experiment functions
from .experiment_functions import (
    query_experiment_by_id,
    query_experiment_by_filters,
    query_experiment_by_additional_data,
    query_experiment_by_additional_metadata,
    query_experiment_by_biosets,
    query_experiment_by_detection_instrument,
    query_experiment_by_doi,
    query_experiment_by_exp_description,
    query_experiment_by_exp_name,
    query_experiment_by_exp_poc,
    query_experiment_by_exp_protocol,
    query_experiment_by_exp_title,
    query_experiment_by_exp_type,
    query_experiment_by_experimenters,
    query_experiment_by_genome_id,
    query_experiment_by_measurement_technique,
    query_experiment_by_organism,
    query_experiment_by_pmid,
    query_experiment_by_public_identifier,
    query_experiment_by_public_repository,
    query_experiment_by_samples,
    query_experiment_by_strain,
    query_experiment_by_study_description,
    query_experiment_by_study_institution,
    query_experiment_by_study_name,
    query_experiment_by_study_pi,
    query_experiment_by_study_title,
    query_experiment_by_taxon_id,
    query_experiment_by_taxon_lineage_ids,
    query_experiment_by_treatment_amount,
    query_experiment_by_treatment_duration,
    query_experiment_by_treatment_name,
    query_experiment_by_treatment_type,
    query_experiment_by_date_inserted_range,
    query_experiment_by_date_modified_range,
    query_experiment_by_biosets_range,
    query_experiment_by_samples_range,
    query_experiment_by_keyword,
    query_experiment_all
)

# Import gene ontology reference functions
from .gene_ontology_ref_functions import (
    query_gene_ontology_ref_by_id,
    query_gene_ontology_ref_by_filters,
    query_gene_ontology_ref_by_go_name,
    query_gene_ontology_ref_by_definition,
    query_gene_ontology_ref_by_ontology,
    query_gene_ontology_ref_by_date_inserted_range,
    query_gene_ontology_ref_by_date_modified_range,
    query_gene_ontology_ref_by_keyword,
    query_gene_ontology_ref_all
)

# Import genome AMR functions
from .genome_amr_functions import (
    query_genome_amr_by_id,
    query_genome_amr_by_filters,
    query_genome_amr_by_antibiotic,
    query_genome_amr_by_computational_method,
    query_genome_amr_by_computational_method_version,
    query_genome_amr_by_evidence,
    query_genome_amr_by_genome_id,
    query_genome_amr_by_genome_name,
    query_genome_amr_by_laboratory_typing_method,
    query_genome_amr_by_laboratory_typing_method_version,
    query_genome_amr_by_laboratory_typing_platform,
    query_genome_amr_by_measurement,
    query_genome_amr_by_measurement_sign,
    query_genome_amr_by_measurement_unit,
    query_genome_amr_by_measurement_value,
    query_genome_amr_by_owner,
    query_genome_amr_by_pmid,
    query_genome_amr_by_public_status,
    query_genome_amr_by_resistant_phenotype,
    query_genome_amr_by_source,
    query_genome_amr_by_taxon_id,
    query_genome_amr_by_testing_standard,
    query_genome_amr_by_testing_standard_year,
    query_genome_amr_by_vendor,
    query_genome_amr_by_date_range,
    query_genome_amr_by_modified_date_range,
    query_genome_amr_by_keyword,
    query_genome_amr_all
)

# Import genome sequence functions
from .genome_sequence_functions import (
    query_genome_sequence_by_id,
    query_genome_sequence_by_filters,
    query_genome_sequence_by_accession,
    query_genome_sequence_by_chromosome,
    query_genome_sequence_by_description,
    query_genome_sequence_by_gc_content,
    query_genome_sequence_by_genome_id,
    query_genome_sequence_by_genome_name,
    query_genome_sequence_by_gi,
    query_genome_sequence_by_length,
    query_genome_sequence_by_mol_type,
    query_genome_sequence_by_owner,
    query_genome_sequence_by_p2_sequence_id,
    query_genome_sequence_by_plasmid,
    query_genome_sequence_by_public_status,
    query_genome_sequence_by_segment,
    query_genome_sequence_by_sequence_md5,
    query_genome_sequence_by_sequence_status,
    query_genome_sequence_by_sequence_type,
    query_genome_sequence_by_taxon_id,
    query_genome_sequence_by_topology,
    query_genome_sequence_by_version,
    query_genome_sequence_by_length_range,
    query_genome_sequence_by_gc_content_range,
    query_genome_sequence_by_date_inserted_range,
    query_genome_sequence_by_date_modified_range,
    query_genome_sequence_by_release_date_range,
    query_genome_sequence_by_keyword,
    query_genome_sequence_all
)

# Import ID reference functions
from .id_ref_functions import (
    query_id_ref_by_id,
    query_id_ref_by_filters,
    query_id_ref_by_id_type,
    query_id_ref_by_id_value,
    query_id_ref_by_uniprotkb_accession,
    query_id_ref_by_date_inserted_range,
    query_id_ref_by_date_modified_range,
    query_id_ref_by_keyword,
    query_id_ref_all
)

# Import miscellaneous NIAID SGC functions
from .misc_niaid_sgc_functions import (
    query_misc_niaid_sgc_by_id,
    query_misc_niaid_sgc_by_filters,
    query_misc_niaid_sgc_by_genus,
    query_misc_niaid_sgc_by_species,
    query_misc_niaid_sgc_by_taxon_id,
    query_misc_niaid_sgc_by_date_inserted_range,
    query_misc_niaid_sgc_by_date_modified_range,
    query_misc_niaid_sgc_by_keyword,
    query_misc_niaid_sgc_all
)

# Import pathway reference functions
from .pathway_ref_functions import (
    query_pathway_ref_by_id,
    query_pathway_ref_by_filters,
    query_pathway_ref_by_ec_number,
    query_pathway_ref_by_ec_description,
    query_pathway_ref_by_map_location,
    query_pathway_ref_by_map_name,
    query_pathway_ref_by_map_type,
    query_pathway_ref_by_occurrence,
    query_pathway_ref_by_pathway_class,
    query_pathway_ref_by_pathway_id,
    query_pathway_ref_by_pathway_name,
    query_pathway_ref_by_occurrence_range,
    query_pathway_ref_by_date_inserted_range,
    query_pathway_ref_by_date_modified_range,
    query_pathway_ref_by_keyword,
    query_pathway_ref_all
)

# Import pathway functions
from .pathway_functions import (
    query_pathway_by_id,
    query_pathway_by_filters,
    query_pathway_by_accession,
    query_pathway_by_alt_locus_tag,
    query_pathway_by_annotation,
    query_pathway_by_ec_description,
    query_pathway_by_ec_number,
    query_pathway_by_feature_id,
    query_pathway_by_gene,
    query_pathway_by_genome_ec,
    query_pathway_by_genome_id,
    query_pathway_by_genome_name,
    query_pathway_by_owner,
    query_pathway_by_pathway_class,
    query_pathway_by_pathway_ec,
    query_pathway_by_pathway_id,
    query_pathway_by_pathway_name,
    query_pathway_by_patric_id,
    query_pathway_by_product,
    query_pathway_by_public_status,
    query_pathway_by_refseq_locus_tag,
    query_pathway_by_sequence_id,
    query_pathway_by_taxon_id,
    query_pathway_by_user_read,
    query_pathway_by_user_write,
    query_pathway_by_version,
    query_pathway_by_date_inserted_range,
    query_pathway_by_date_modified_range,
    query_pathway_by_keyword,
    query_pathway_all
)

# Import protein-protein interaction functions
from .ppi_functions import (
    query_ppi_by_id,
    query_ppi_by_filters,
    query_ppi_by_category,
    query_ppi_by_detection_method,
    query_ppi_by_domain_a,
    query_ppi_by_domain_b,
    query_ppi_by_evidence,
    query_ppi_by_feature_id_a,
    query_ppi_by_feature_id_b,
    query_ppi_by_gene_a,
    query_ppi_by_gene_b,
    query_ppi_by_genome_id_a,
    query_ppi_by_genome_id_b,
    query_ppi_by_genome_name_a,
    query_ppi_by_genome_name_b,
    query_ppi_by_interaction_type,
    query_ppi_by_interactor_a,
    query_ppi_by_interactor_b,
    query_ppi_by_pmid,
    query_ppi_by_source_db,
    query_ppi_by_source_id,
    query_ppi_by_taxon_id_a,
    query_ppi_by_taxon_id_b,
    query_ppi_by_date_inserted_range,
    query_ppi_by_date_modified_range,
    query_ppi_by_keyword,
    query_ppi_all
)

# Import protein family reference functions
from .protein_family_ref_functions import (
    query_protein_family_ref_by_id,
    query_protein_family_ref_by_filters,
    query_protein_family_ref_by_family_product,
    query_protein_family_ref_by_family_type,
    query_protein_family_ref_by_date_inserted_range,
    query_protein_family_ref_by_date_modified_range,
    query_protein_family_ref_by_keyword,
    query_protein_family_ref_all
)

# Import protein feature functions
from .protein_feature_functions import (
    query_protein_feature_by_id,
    query_protein_feature_by_filters,
    query_protein_feature_by_aa_sequence_md5,
    query_protein_feature_by_classification,
    query_protein_feature_by_comment,
    query_protein_feature_by_description,
    query_protein_feature_by_e_value,
    query_protein_feature_by_end,
    query_protein_feature_by_evidence,
    query_protein_feature_by_feature_id,
    query_protein_feature_by_feature_type,
    query_protein_feature_by_gene,
    query_protein_feature_by_genome_id,
    query_protein_feature_by_genome_name,
    query_protein_feature_by_interpro_description,
    query_protein_feature_by_interpro_id,
    query_protein_feature_by_length,
    query_protein_feature_by_patric_id,
    query_protein_feature_by_product,
    query_protein_feature_by_publication,
    query_protein_feature_by_refseq_locus_tag,
    query_protein_feature_by_score,
    query_protein_feature_by_segment,
    query_protein_feature_by_sequence,
    query_protein_feature_by_source,
    query_protein_feature_by_source_id,
    query_protein_feature_by_start,
    query_protein_feature_by_taxon_id,
    query_protein_feature_by_score_range,
    query_protein_feature_by_length_range,
    query_protein_feature_by_position_range,
    query_protein_feature_by_date_inserted_range,
    query_protein_feature_by_date_modified_range,
    query_protein_feature_by_keyword,
    query_protein_feature_all
)

# Import protein structure functions
from .protein_structure_functions import (
    query_protein_structure_by_id,
    query_protein_structure_by_filters,
    query_protein_structure_by_feature_id,
    query_protein_structure_by_genome_id,
    query_protein_structure_by_patric_id,
    query_protein_structure_by_organism_name,
    query_protein_structure_by_title,
    query_protein_structure_by_resolution,
    query_protein_structure_by_institution,
    query_protein_structure_by_file_path,
    query_protein_structure_by_author,
    query_protein_structure_by_method,
    query_protein_structure_by_gene,
    query_protein_structure_by_product,
    query_protein_structure_by_sequence,
    query_protein_structure_by_sequence_md5,
    query_protein_structure_by_uniprotkb_accession,
    query_protein_structure_by_pmid,
    query_protein_structure_by_taxon_id,
    query_protein_structure_by_taxon_lineage_id,
    query_protein_structure_by_taxon_lineage_name,
    query_protein_structure_by_alignment,
    query_protein_structure_by_release_date_range,
    query_protein_structure_by_date_inserted_range,
    query_protein_structure_by_date_modified_range,
    query_protein_structure_by_keyword,
    query_protein_structure_all
)

# Import sequence feature VT functions
from .sequence_feature_vt_functions import (
    query_sequence_feature_vt_by_id,
    query_sequence_feature_vt_by_filters,
    query_sequence_feature_vt_by_sf_category,
    query_sequence_feature_vt_by_genome_id,
    query_sequence_feature_vt_by_taxon_id,
    query_sequence_feature_vt_by_date_inserted_range,
    query_sequence_feature_vt_by_date_modified_range,
    query_sequence_feature_vt_by_keyword,
    query_sequence_feature_vt_all
)

# Import sequence feature functions
from .sequence_feature_functions import (
    query_sequence_feature_by_id,
    query_sequence_feature_by_filters,
    query_sequence_feature_by_feature_id,
    query_sequence_feature_by_genome_id,
    query_sequence_feature_by_genome_name,
    query_sequence_feature_by_gene,
    query_sequence_feature_by_product,
    query_sequence_feature_by_patric_id,
    query_sequence_feature_by_genbank_accession,
    query_sequence_feature_by_refseq_locus_tag,
    query_sequence_feature_by_sf_category,
    query_sequence_feature_by_sf_id,
    query_sequence_feature_by_sf_name,
    query_sequence_feature_by_source,
    query_sequence_feature_by_source_id,
    query_sequence_feature_by_source_strain,
    query_sequence_feature_by_segment,
    query_sequence_feature_by_subtype,
    query_sequence_feature_by_taxon_id,
    query_sequence_feature_by_evidence_code,
    query_sequence_feature_by_aa_sequence_md5,
    query_sequence_feature_by_aa_variant,
    query_sequence_feature_by_sf_sequence_md5,
    query_sequence_feature_by_source_aa_sequence,
    query_sequence_feature_by_source_sf_location,
    query_sequence_feature_by_variant_types,
    query_sequence_feature_by_start,
    query_sequence_feature_by_end,
    query_sequence_feature_by_length,
    query_sequence_feature_by_position_range,
    query_sequence_feature_by_length_range,
    query_sequence_feature_by_date_range,
    query_sequence_feature_by_modified_date_range,
    query_sequence_feature_by_keyword,
    query_sequence_feature_all
)

# Import serology functions
from .serology_functions import (
    query_serology_by_id,
    query_serology_by_filters,
    query_serology_by_additional_metadata,
    query_serology_by_collection_city,
    query_serology_by_collection_country,
    query_serology_by_collection_state,
    query_serology_by_collection_year,
    query_serology_by_comments,
    query_serology_by_contributing_institution,
    query_serology_by_genbank_accession,
    query_serology_by_geographic_group,
    query_serology_by_host_age,
    query_serology_by_host_age_group,
    query_serology_by_host_common_name,
    query_serology_by_host_health,
    query_serology_by_host_identifier,
    query_serology_by_host_sex,
    query_serology_by_host_species,
    query_serology_by_host_type,
    query_serology_by_positive_definition,
    query_serology_by_project_identifier,
    query_serology_by_sample_accession,
    query_serology_by_sample_identifier,
    query_serology_by_serotype,
    query_serology_by_strain,
    query_serology_by_taxon_lineage_id,
    query_serology_by_test_antigen,
    query_serology_by_test_interpretation,
    query_serology_by_test_pathogen,
    query_serology_by_test_result,
    query_serology_by_test_type,
    query_serology_by_virus_identifier,
    query_serology_by_collection_date_range,
    query_serology_by_date_inserted_range,
    query_serology_by_date_modified_range,
    query_serology_by_keyword,
    query_serology_all
)

# Import SP gene reference functions
from .sp_gene_ref_functions import (
    query_sp_gene_ref_by_id,
    query_sp_gene_ref_by_filters,
    query_sp_gene_ref_by_antibiotics,
    query_sp_gene_ref_by_gene_symbol,
    query_sp_gene_ref_by_source,
    query_sp_gene_ref_by_taxon_id,
    query_sp_gene_ref_by_date_inserted_range,
    query_sp_gene_ref_by_date_modified_range,
    query_sp_gene_ref_by_keyword,
    query_sp_gene_ref_all
)

# Import SP gene functions
from .sp_gene_functions import (
    query_sp_gene_by_id,
    query_sp_gene_by_filters,
    query_sp_gene_by_genome_id,
    query_sp_gene_by_gene,
    query_sp_gene_by_taxon_id,
    query_sp_gene_by_date_inserted_range,
    query_sp_gene_by_date_modified_range,
    query_sp_gene_by_keyword,
    query_sp_gene_all
)

# Import spike lineage functions
from .spike_lineage_functions import (
    query_spike_lineage_by_id,
    query_spike_lineage_by_filters,
    query_spike_lineage_by_country,
    query_spike_lineage_by_growth_rate,
    query_spike_lineage_by_lineage,
    query_spike_lineage_by_lineage_count,
    query_spike_lineage_by_lineage_of_concern,
    query_spike_lineage_by_month,
    query_spike_lineage_by_prevalence,
    query_spike_lineage_by_region,
    query_spike_lineage_by_sequence_features,
    query_spike_lineage_by_total_isolates,
    query_spike_lineage_by_growth_rate_range,
    query_spike_lineage_by_lineage_count_range,
    query_spike_lineage_by_prevalence_range,
    query_spike_lineage_by_total_isolates_range,
    query_spike_lineage_by_date_inserted_range,
    query_spike_lineage_by_date_modified_range,
    query_spike_lineage_by_keyword,
    query_spike_lineage_all
)

# Import spike variant functions
from .spike_variant_functions import (
    query_spike_variant_by_id,
    query_spike_variant_by_filters,
    query_spike_variant_by_aa_variant,
    query_spike_variant_by_country,
    query_spike_variant_by_region,
    query_spike_variant_by_month,
    query_spike_variant_by_sequence_feature,
    query_spike_variant_by_growth_rate,
    query_spike_variant_by_prevalence,
    query_spike_variant_by_lineage_count,
    query_spike_variant_by_total_isolates,
    query_spike_variant_by_growth_rate_range,
    query_spike_variant_by_prevalence_range,
    query_spike_variant_by_lineage_count_range,
    query_spike_variant_by_total_isolates_range,
    query_spike_variant_by_date_range,
    query_spike_variant_by_modified_date_range,
    query_spike_variant_by_keyword,
    query_spike_variant_all
)

# Import strain functions
from .strain_functions import (
    query_strain_by_id,
    query_strain_by_filters,
    query_strain_by_collection_date,
    query_strain_by_collection_year,
    query_strain_by_family,
    query_strain_by_genus,
    query_strain_by_species,
    query_strain_by_strain,
    query_strain_by_subtype,
    query_strain_by_taxon_id,
    query_strain_by_geographic_group,
    query_strain_by_isolation_country,
    query_strain_by_host_common_name,
    query_strain_by_host_group,
    query_strain_by_host_name,
    query_strain_by_lab_host,
    query_strain_by_owner,
    query_strain_by_status,
    query_strain_by_public,
    query_strain_by_collection_year_range,
    query_strain_by_date_inserted_range,
    query_strain_by_date_modified_range,
    query_strain_by_h_type_range,
    query_strain_by_n_type_range,
    query_strain_by_segment_count_range,
    query_strain_by_taxon_id_range,
    query_strain_by_keyword,
    query_strain_all
)

# Import structured assertion functions
from .structured_assertion_functions import (
    query_structured_assertion_by_id,
    query_structured_assertion_by_filters,
    query_structured_assertion_by_comment,
    query_structured_assertion_by_evidence_code,
    query_structured_assertion_by_feature_id,
    query_structured_assertion_by_owner,
    query_structured_assertion_by_patric_id,
    query_structured_assertion_by_pmid,
    query_structured_assertion_by_property,
    query_structured_assertion_by_public_status,
    query_structured_assertion_by_refseq_locus_tag,
    query_structured_assertion_by_score,
    query_structured_assertion_by_source,
    query_structured_assertion_by_value,
    query_structured_assertion_by_user_read,
    query_structured_assertion_by_user_write,
    query_structured_assertion_by_version,
    query_structured_assertion_by_date_inserted_range,
    query_structured_assertion_by_date_modified_range,
    query_structured_assertion_by_keyword,
    query_structured_assertion_all
)

# Import subsystem reference functions
from .subsystem_ref_functions import (
    query_subsystem_ref_by_id,
    query_subsystem_ref_by_filters,
    query_subsystem_ref_by_class,
    query_subsystem_ref_by_description,
    query_subsystem_ref_by_role,
    query_subsystem_ref_by_role_id,
    query_subsystem_ref_by_subsystem_id,
    query_subsystem_ref_by_subsystem_name,
    query_subsystem_ref_by_superclass,
    query_subsystem_ref_by_date_inserted_range,
    query_subsystem_ref_by_date_modified_range,
    query_subsystem_ref_by_keyword,
    query_subsystem_ref_all
)

# Import subsystem functions
from .subsystem_functions import (
    query_subsystem_by_id,
    query_subsystem_by_filters,
    query_subsystem_by_active,
    query_subsystem_by_class,
    query_subsystem_by_feature_id,
    query_subsystem_by_gene,
    query_subsystem_by_genome_id,
    query_subsystem_by_genome_name,
    query_subsystem_by_owner,
    query_subsystem_by_patric_id,
    query_subsystem_by_product,
    query_subsystem_by_public_status,
    query_subsystem_by_refseq_locus_tag,
    query_subsystem_by_role_id,
    query_subsystem_by_role_name,
    query_subsystem_by_subclass,
    query_subsystem_by_subsystem_id,
    query_subsystem_by_subsystem_name,
    query_subsystem_by_superclass,
    query_subsystem_by_taxon_id,
    query_subsystem_by_user_read,
    query_subsystem_by_user_write,
    query_subsystem_by_date_inserted_range,
    query_subsystem_by_date_modified_range,
    query_subsystem_by_keyword,
    query_subsystem_all
)

# Import surveillance functions
from .surveillance_functions import (
    query_surveillance_by_id,
    query_surveillance_by_filters,
    query_surveillance_by_host_species,
    query_surveillance_by_host_common_name,
    query_surveillance_by_sample_identifier,
    query_surveillance_by_sample_accession,
    query_surveillance_by_collection_country,
    query_surveillance_by_collection_city,
    query_surveillance_by_collection_year,
    query_surveillance_by_species,
    query_surveillance_by_strain,
    query_surveillance_by_subtype,
    query_surveillance_by_pathogen_type,
    query_surveillance_by_genome_id,
    query_surveillance_by_disease_status,
    query_surveillance_by_diagnosis,
    query_surveillance_by_treatment,
    query_surveillance_by_hospitalized,
    query_surveillance_by_vaccination_type,
    query_surveillance_by_exposure,
    query_surveillance_by_pathogen_test_type,
    query_surveillance_by_pathogen_test_result,
    query_surveillance_by_collection_date_range,
    query_surveillance_by_date_inserted_range,
    query_surveillance_by_date_modified_range,
    query_surveillance_by_keyword,
    query_surveillance_all
)

# Import taxonomy functions
from .taxonomy_functions import (
    query_taxonomy_by_id,
    query_taxonomy_by_filters,
    query_taxonomy_by_taxon_name,
    query_taxonomy_by_taxon_rank,
    query_taxonomy_by_lineage,
    query_taxonomy_by_lineage_ids,
    query_taxonomy_by_lineage_names,
    query_taxonomy_by_parent_id,
    query_taxonomy_by_division,
    query_taxonomy_by_genetic_code,
    query_taxonomy_by_genome_count,
    query_taxonomy_by_core_families,
    query_taxonomy_by_cds_mean,
    query_taxonomy_by_genome_length_mean,
    query_taxonomy_by_cds_mean_range,
    query_taxonomy_by_core_families_range,
    query_taxonomy_by_genetic_code_range,
    query_taxonomy_by_genome_count_range,
    query_taxonomy_by_genome_length_mean_range,
    query_taxonomy_by_parent_id_range,
    query_taxonomy_by_keyword,
    query_taxonomy_all
)

__all__ = [
    # Common functions
    'create_bvbrc_client',
    'query_direct',
    'format_query_result',
    
    # Genome functions
    'query_genome_by_id',
    'query_genome_by_taxon_id',
    'query_genome_by_genome_name',
    'query_genome_by_species',
    'query_genome_by_genus',
    'query_genome_by_filters',
    
    # Genome feature functions
    'query_genome_feature_by_id',
    'query_genome_feature_by_genome_id',
    'query_genome_feature_by_gene',
    'query_genome_feature_by_product',
    'query_genome_feature_by_filters',
    
    # Antibiotics functions
    'query_antibiotics_by_pubchem_cid',
    'query_antibiotics_by_filters',
    'query_antibiotics_by_keyword',
    'query_antibiotics_by_name',
    'query_antibiotics_by_cas_id',
    'query_antibiotics_by_molecular_formula',
    'query_antibiotics_by_atc_classification',
    'query_antibiotics_by_mechanism_of_action',
    'query_antibiotics_by_pharmacological_class',
    'query_antibiotics_by_synonym',
    'query_antibiotics_by_molecular_weight_range',
    'query_antibiotics_by_date_range',
    'query_antibiotics_all',
    
    # Bioset functions
    'query_bioset_by_id',
    'query_bioset_by_filters',
    'query_bioset_by_name',
    'query_bioset_by_type',
    'query_bioset_by_exp_id',
    'query_bioset_by_exp_name',
    'query_bioset_by_exp_type',
    'query_bioset_by_organism',
    'query_bioset_by_strain',
    'query_bioset_by_taxon_id',
    'query_bioset_by_entity_type',
    'query_bioset_by_result_type',
    'query_bioset_by_analysis_method',
    'query_bioset_by_analysis_group_1',
    'query_bioset_by_analysis_group_2',
    'query_bioset_by_treatment_type',
    'query_bioset_by_treatment_name',
    'query_bioset_by_study_name',
    'query_bioset_by_study_pi',
    'query_bioset_by_study_institution',
    'query_bioset_by_genome_id',
    'query_bioset_by_date_range',
    'query_bioset_by_modified_date_range',
    'query_bioset_by_keyword',
    'query_bioset_all',
    
    # Enzyme class reference functions
    'query_enzyme_class_ref_by_ec_number',
    'query_enzyme_class_ref_by_filters',
    'query_enzyme_class_ref_by_ec_description',
    'query_enzyme_class_ref_by_go_term',
    'query_enzyme_class_ref_by_version',
    'query_enzyme_class_ref_by_date_inserted_range',
    'query_enzyme_class_ref_by_date_modified_range',
    'query_enzyme_class_ref_by_keyword',
    'query_enzyme_class_ref_all',
    
    # Epitope assay functions
    'query_epitope_assay_by_id',
    'query_epitope_assay_by_filters',
    'query_epitope_assay_by_assay_group',
    'query_epitope_assay_by_assay_measurement',
    'query_epitope_assay_by_assay_measurement_unit',
    'query_epitope_assay_by_assay_method',
    'query_epitope_assay_by_assay_result',
    'query_epitope_assay_by_assay_type',
    'query_epitope_assay_by_authors',
    'query_epitope_assay_by_epitope_id',
    'query_epitope_assay_by_epitope_sequence',
    'query_epitope_assay_by_epitope_type',
    'query_epitope_assay_by_host_name',
    'query_epitope_assay_by_host_taxon_id',
    'query_epitope_assay_by_mhc_allele',
    'query_epitope_assay_by_mhc_allele_class',
    'query_epitope_assay_by_organism',
    'query_epitope_assay_by_pdb_id',
    'query_epitope_assay_by_pmid',
    'query_epitope_assay_by_protein_accession',
    'query_epitope_assay_by_protein_id',
    'query_epitope_assay_by_protein_name',
    'query_epitope_assay_by_start',
    'query_epitope_assay_by_end',
    'query_epitope_assay_by_taxon_id',
    'query_epitope_assay_by_taxon_lineage_id',
    'query_epitope_assay_by_taxon_lineage_name',
    'query_epitope_assay_by_title',
    'query_epitope_assay_by_position_range',
    'query_epitope_assay_by_date_inserted_range',
    'query_epitope_assay_by_date_modified_range',
    'query_epitope_assay_by_keyword',
    'query_epitope_assay_all',
    
    # Epitope functions
    'query_epitope_by_id',
    'query_epitope_by_filters',
    'query_epitope_by_epitope_sequence',
    'query_epitope_by_epitope_type',
    'query_epitope_by_host_name',
    'query_epitope_by_organism',
    'query_epitope_by_protein_accession',
    'query_epitope_by_protein_id',
    'query_epitope_by_protein_name',
    'query_epitope_by_start',
    'query_epitope_by_end',
    'query_epitope_by_taxon_id',
    'query_epitope_by_bcell_assays',
    'query_epitope_by_mhc_assays',
    'query_epitope_by_tcell_assays',
    'query_epitope_by_total_assays',
    'query_epitope_by_comment',
    'query_epitope_by_assay_result',
    'query_epitope_by_taxon_lineage_id',
    'query_epitope_by_taxon_lineage_name',
    'query_epitope_by_position_range',
    'query_epitope_by_total_assays_range',
    'query_epitope_by_date_inserted_range',
    'query_epitope_by_date_modified_range',
    'query_epitope_by_keyword',
    'query_epitope_all',
    
    # Experiment functions
    'query_experiment_by_id',
    'query_experiment_by_filters',
    'query_experiment_by_additional_data',
    'query_experiment_by_additional_metadata',
    'query_experiment_by_biosets',
    'query_experiment_by_detection_instrument',
    'query_experiment_by_doi',
    'query_experiment_by_exp_description',
    'query_experiment_by_exp_name',
    'query_experiment_by_exp_poc',
    'query_experiment_by_exp_protocol',
    'query_experiment_by_exp_title',
    'query_experiment_by_exp_type',
    'query_experiment_by_experimenters',
    'query_experiment_by_genome_id',
    'query_experiment_by_measurement_technique',
    'query_experiment_by_organism',
    'query_experiment_by_pmid',
    'query_experiment_by_public_identifier',
    'query_experiment_by_public_repository',
    'query_experiment_by_samples',
    'query_experiment_by_strain',
    'query_experiment_by_study_description',
    'query_experiment_by_study_institution',
    'query_experiment_by_study_name',
    'query_experiment_by_study_pi',
    'query_experiment_by_study_title',
    'query_experiment_by_taxon_id',
    'query_experiment_by_taxon_lineage_ids',
    'query_experiment_by_treatment_amount',
    'query_experiment_by_treatment_duration',
    'query_experiment_by_treatment_name',
    'query_experiment_by_treatment_type',
    'query_experiment_by_date_inserted_range',
    'query_experiment_by_date_modified_range',
    'query_experiment_by_biosets_range',
    'query_experiment_by_samples_range',
    'query_experiment_by_keyword',
    'query_experiment_all',
    
    # Gene ontology reference functions
    'query_gene_ontology_ref_by_id',
    'query_gene_ontology_ref_by_filters',
    'query_gene_ontology_ref_by_go_name',
    'query_gene_ontology_ref_by_definition',
    'query_gene_ontology_ref_by_ontology',
    'query_gene_ontology_ref_by_date_inserted_range',
    'query_gene_ontology_ref_by_date_modified_range',
    'query_gene_ontology_ref_by_keyword',
    'query_gene_ontology_ref_all',
    
    # Genome AMR functions
    'query_genome_amr_by_id',
    'query_genome_amr_by_filters',
    'query_genome_amr_by_antibiotic',
    'query_genome_amr_by_computational_method',
    'query_genome_amr_by_computational_method_version',
    'query_genome_amr_by_evidence',
    'query_genome_amr_by_genome_id',
    'query_genome_amr_by_genome_name',
    'query_genome_amr_by_laboratory_typing_method',
    'query_genome_amr_by_laboratory_typing_method_version',
    'query_genome_amr_by_laboratory_typing_platform',
    'query_genome_amr_by_measurement',
    'query_genome_amr_by_measurement_sign',
    'query_genome_amr_by_measurement_unit',
    'query_genome_amr_by_measurement_value',
    'query_genome_amr_by_owner',
    'query_genome_amr_by_pmid',
    'query_genome_amr_by_public_status',
    'query_genome_amr_by_resistant_phenotype',
    'query_genome_amr_by_source',
    'query_genome_amr_by_taxon_id',
    'query_genome_amr_by_testing_standard',
    'query_genome_amr_by_testing_standard_year',
    'query_genome_amr_by_vendor',
    'query_genome_amr_by_date_range',
    'query_genome_amr_by_modified_date_range',
    'query_genome_amr_by_keyword',
    'query_genome_amr_all',
    
    # Genome sequence functions
    'query_genome_sequence_by_id',
    'query_genome_sequence_by_filters',
    'query_genome_sequence_by_accession',
    'query_genome_sequence_by_chromosome',
    'query_genome_sequence_by_description',
    'query_genome_sequence_by_gc_content',
    'query_genome_sequence_by_genome_id',
    'query_genome_sequence_by_genome_name',
    'query_genome_sequence_by_gi',
    'query_genome_sequence_by_length',
    'query_genome_sequence_by_mol_type',
    'query_genome_sequence_by_owner',
    'query_genome_sequence_by_p2_sequence_id',
    'query_genome_sequence_by_plasmid',
    'query_genome_sequence_by_public_status',
    'query_genome_sequence_by_segment',
    'query_genome_sequence_by_sequence_md5',
    'query_genome_sequence_by_sequence_status',
    'query_genome_sequence_by_sequence_type',
    'query_genome_sequence_by_taxon_id',
    'query_genome_sequence_by_topology',
    'query_genome_sequence_by_version',
    'query_genome_sequence_by_length_range',
    'query_genome_sequence_by_gc_content_range',
    'query_genome_sequence_by_date_inserted_range',
    'query_genome_sequence_by_date_modified_range',
    'query_genome_sequence_by_release_date_range',
    'query_genome_sequence_by_keyword',
    'query_genome_sequence_all',
    
    # ID reference functions
    'query_id_ref_by_id',
    'query_id_ref_by_filters',
    'query_id_ref_by_id_type',
    'query_id_ref_by_id_value',
    'query_id_ref_by_uniprotkb_accession',
    'query_id_ref_by_date_inserted_range',
    'query_id_ref_by_date_modified_range',
    'query_id_ref_by_keyword',
    'query_id_ref_all',
    
    # Miscellaneous NIAID SGC functions
    'query_misc_niaid_sgc_by_id',
    'query_misc_niaid_sgc_by_filters',
    'query_misc_niaid_sgc_by_genus',
    'query_misc_niaid_sgc_by_species',
    'query_misc_niaid_sgc_by_taxon_id',
    'query_misc_niaid_sgc_by_date_inserted_range',
    'query_misc_niaid_sgc_by_date_modified_range',
    'query_misc_niaid_sgc_by_keyword',
    'query_misc_niaid_sgc_all',
    
    # Pathway reference functions
    'query_pathway_ref_by_id',
    'query_pathway_ref_by_filters',
    'query_pathway_ref_by_ec_number',
    'query_pathway_ref_by_ec_description',
    'query_pathway_ref_by_map_location',
    'query_pathway_ref_by_map_name',
    'query_pathway_ref_by_map_type',
    'query_pathway_ref_by_occurrence',
    'query_pathway_ref_by_pathway_class',
    'query_pathway_ref_by_pathway_id',
    'query_pathway_ref_by_pathway_name',
    'query_pathway_ref_by_occurrence_range',
    'query_pathway_ref_by_date_inserted_range',
    'query_pathway_ref_by_date_modified_range',
    'query_pathway_ref_by_keyword',
    'query_pathway_ref_all',
    
    # Pathway functions
    'query_pathway_by_id',
    'query_pathway_by_filters',
    'query_pathway_by_accession',
    'query_pathway_by_alt_locus_tag',
    'query_pathway_by_annotation',
    'query_pathway_by_ec_description',
    'query_pathway_by_ec_number',
    'query_pathway_by_feature_id',
    'query_pathway_by_gene',
    'query_pathway_by_genome_ec',
    'query_pathway_by_genome_id',
    'query_pathway_by_genome_name',
    'query_pathway_by_owner',
    'query_pathway_by_pathway_class',
    'query_pathway_by_pathway_ec',
    'query_pathway_by_pathway_id',
    'query_pathway_by_pathway_name',
    'query_pathway_by_patric_id',
    'query_pathway_by_product',
    'query_pathway_by_public_status',
    'query_pathway_by_refseq_locus_tag',
    'query_pathway_by_sequence_id',
    'query_pathway_by_taxon_id',
    'query_pathway_by_user_read',
    'query_pathway_by_user_write',
    'query_pathway_by_version',
    'query_pathway_by_date_inserted_range',
    'query_pathway_by_date_modified_range',
    'query_pathway_by_keyword',
    'query_pathway_all',
    
    # Protein-protein interaction functions
    'query_ppi_by_id',
    'query_ppi_by_filters',
    'query_ppi_by_category',
    'query_ppi_by_detection_method',
    'query_ppi_by_domain_a',
    'query_ppi_by_domain_b',
    'query_ppi_by_evidence',
    'query_ppi_by_feature_id_a',
    'query_ppi_by_feature_id_b',
    'query_ppi_by_gene_a',
    'query_ppi_by_gene_b',
    'query_ppi_by_genome_id_a',
    'query_ppi_by_genome_id_b',
    'query_ppi_by_genome_name_a',
    'query_ppi_by_genome_name_b',
    'query_ppi_by_interaction_type',
    'query_ppi_by_interactor_a',
    'query_ppi_by_interactor_b',
    'query_ppi_by_pmid',
    'query_ppi_by_source_db',
    'query_ppi_by_source_id',
    'query_ppi_by_taxon_id_a',
    'query_ppi_by_taxon_id_b',
    'query_ppi_by_date_inserted_range',
    'query_ppi_by_date_modified_range',
    'query_ppi_by_keyword',
    'query_ppi_all',
    
    # Protein family reference functions
    'query_protein_family_ref_by_id',
    'query_protein_family_ref_by_filters',
    'query_protein_family_ref_by_family_product',
    'query_protein_family_ref_by_family_type',
    'query_protein_family_ref_by_date_inserted_range',
    'query_protein_family_ref_by_date_modified_range',
    'query_protein_family_ref_by_keyword',
    'query_protein_family_ref_all',
    
    # Protein feature functions
    'query_protein_feature_by_id',
    'query_protein_feature_by_filters',
    'query_protein_feature_by_aa_sequence_md5',
    'query_protein_feature_by_classification',
    'query_protein_feature_by_comment',
    'query_protein_feature_by_description',
    'query_protein_feature_by_e_value',
    'query_protein_feature_by_end',
    'query_protein_feature_by_evidence',
    'query_protein_feature_by_feature_id',
    'query_protein_feature_by_feature_type',
    'query_protein_feature_by_gene',
    'query_protein_feature_by_genome_id',
    'query_protein_feature_by_genome_name',
    'query_protein_feature_by_interpro_description',
    'query_protein_feature_by_interpro_id',
    'query_protein_feature_by_length',
    'query_protein_feature_by_patric_id',
    'query_protein_feature_by_product',
    'query_protein_feature_by_publication',
    'query_protein_feature_by_refseq_locus_tag',
    'query_protein_feature_by_score',
    'query_protein_feature_by_segment',
    'query_protein_feature_by_sequence',
    'query_protein_feature_by_source',
    'query_protein_feature_by_source_id',
    'query_protein_feature_by_start',
    'query_protein_feature_by_taxon_id',
    'query_protein_feature_by_score_range',
    'query_protein_feature_by_length_range',
    'query_protein_feature_by_position_range',
    'query_protein_feature_by_date_inserted_range',
    'query_protein_feature_by_date_modified_range',
    'query_protein_feature_by_keyword',
    'query_protein_feature_all',
    
    # Protein structure functions
    'query_protein_structure_by_id',
    'query_protein_structure_by_filters',
    'query_protein_structure_by_feature_id',
    'query_protein_structure_by_genome_id',
    'query_protein_structure_by_patric_id',
    'query_protein_structure_by_organism_name',
    'query_protein_structure_by_title',
    'query_protein_structure_by_resolution',
    'query_protein_structure_by_institution',
    'query_protein_structure_by_file_path',
    'query_protein_structure_by_author',
    'query_protein_structure_by_method',
    'query_protein_structure_by_gene',
    'query_protein_structure_by_product',
    'query_protein_structure_by_sequence',
    'query_protein_structure_by_sequence_md5',
    'query_protein_structure_by_uniprotkb_accession',
    'query_protein_structure_by_pmid',
    'query_protein_structure_by_taxon_id',
    'query_protein_structure_by_taxon_lineage_id',
    'query_protein_structure_by_taxon_lineage_name',
    'query_protein_structure_by_alignment',
    'query_protein_structure_by_release_date_range',
    'query_protein_structure_by_date_inserted_range',
    'query_protein_structure_by_date_modified_range',
    'query_protein_structure_by_keyword',
    'query_protein_structure_all',
    
    # Sequence feature VT functions
    'query_sequence_feature_vt_by_id',
    'query_sequence_feature_vt_by_filters',
    'query_sequence_feature_vt_by_sf_category',
    'query_sequence_feature_vt_by_genome_id',
    'query_sequence_feature_vt_by_taxon_id',
    'query_sequence_feature_vt_by_date_inserted_range',
    'query_sequence_feature_vt_by_date_modified_range',
    'query_sequence_feature_vt_by_keyword',
    'query_sequence_feature_vt_all',
    
    # Sequence feature functions
    'query_sequence_feature_by_id',
    'query_sequence_feature_by_filters',
    'query_sequence_feature_by_feature_id',
    'query_sequence_feature_by_genome_id',
    'query_sequence_feature_by_genome_name',
    'query_sequence_feature_by_gene',
    'query_sequence_feature_by_product',
    'query_sequence_feature_by_patric_id',
    'query_sequence_feature_by_genbank_accession',
    'query_sequence_feature_by_refseq_locus_tag',
    'query_sequence_feature_by_sf_category',
    'query_sequence_feature_by_sf_id',
    'query_sequence_feature_by_sf_name',
    'query_sequence_feature_by_source',
    'query_sequence_feature_by_source_id',
    'query_sequence_feature_by_source_strain',
    'query_sequence_feature_by_segment',
    'query_sequence_feature_by_subtype',
    'query_sequence_feature_by_taxon_id',
    'query_sequence_feature_by_evidence_code',
    'query_sequence_feature_by_aa_sequence_md5',
    'query_sequence_feature_by_aa_variant',
    'query_sequence_feature_by_sf_sequence_md5',
    'query_sequence_feature_by_source_aa_sequence',
    'query_sequence_feature_by_source_sf_location',
    'query_sequence_feature_by_variant_types',
    'query_sequence_feature_by_start',
    'query_sequence_feature_by_end',
    'query_sequence_feature_by_length',
    'query_sequence_feature_by_position_range',
    'query_sequence_feature_by_length_range',
    'query_sequence_feature_by_date_range',
    'query_sequence_feature_by_modified_date_range',
    'query_sequence_feature_by_keyword',
    'query_sequence_feature_all',
    
    # Serology functions
    'query_serology_by_id',
    'query_serology_by_filters',
    'query_serology_by_additional_metadata',
    'query_serology_by_collection_city',
    'query_serology_by_collection_country',
    'query_serology_by_collection_state',
    'query_serology_by_collection_year',
    'query_serology_by_comments',
    'query_serology_by_contributing_institution',
    'query_serology_by_genbank_accession',
    'query_serology_by_geographic_group',
    'query_serology_by_host_age',
    'query_serology_by_host_age_group',
    'query_serology_by_host_common_name',
    'query_serology_by_host_health',
    'query_serology_by_host_identifier',
    'query_serology_by_host_sex',
    'query_serology_by_host_species',
    'query_serology_by_host_type',
    'query_serology_by_positive_definition',
    'query_serology_by_project_identifier',
    'query_serology_by_sample_accession',
    'query_serology_by_sample_identifier',
    'query_serology_by_serotype',
    'query_serology_by_strain',
    'query_serology_by_taxon_lineage_id',
    'query_serology_by_test_antigen',
    'query_serology_by_test_interpretation',
    'query_serology_by_test_pathogen',
    'query_serology_by_test_result',
    'query_serology_by_test_type',
    'query_serology_by_virus_identifier',
    'query_serology_by_collection_date_range',
    'query_serology_by_date_inserted_range',
    'query_serology_by_date_modified_range',
    'query_serology_by_keyword',
    'query_serology_all',
    
    # SP gene reference functions
    'query_sp_gene_ref_by_id',
    'query_sp_gene_ref_by_filters',
    'query_sp_gene_ref_by_antibiotics',
    'query_sp_gene_ref_by_gene_symbol',
    'query_sp_gene_ref_by_source',
    'query_sp_gene_ref_by_taxon_id',
    'query_sp_gene_ref_by_date_inserted_range',
    'query_sp_gene_ref_by_date_modified_range',
    'query_sp_gene_ref_by_keyword',
    'query_sp_gene_ref_all',
    
    # SP gene functions
    'query_sp_gene_by_id',
    'query_sp_gene_by_filters',
    'query_sp_gene_by_genome_id',
    'query_sp_gene_by_gene',
    'query_sp_gene_by_taxon_id',
    'query_sp_gene_by_date_inserted_range',
    'query_sp_gene_by_date_modified_range',
    'query_sp_gene_by_keyword',
    'query_sp_gene_all',
    
    # Spike lineage functions
    'query_spike_lineage_by_id',
    'query_spike_lineage_by_filters',
    'query_spike_lineage_by_country',
    'query_spike_lineage_by_growth_rate',
    'query_spike_lineage_by_lineage',
    'query_spike_lineage_by_lineage_count',
    'query_spike_lineage_by_lineage_of_concern',
    'query_spike_lineage_by_month',
    'query_spike_lineage_by_prevalence',
    'query_spike_lineage_by_region',
    'query_spike_lineage_by_sequence_features',
    'query_spike_lineage_by_total_isolates',
    'query_spike_lineage_by_growth_rate_range',
    'query_spike_lineage_by_lineage_count_range',
    'query_spike_lineage_by_prevalence_range',
    'query_spike_lineage_by_total_isolates_range',
    'query_spike_lineage_by_date_inserted_range',
    'query_spike_lineage_by_date_modified_range',
    'query_spike_lineage_by_keyword',
    'query_spike_lineage_all',
    
    # Spike variant functions
    'query_spike_variant_by_id',
    'query_spike_variant_by_filters',
    'query_spike_variant_by_aa_variant',
    'query_spike_variant_by_country',
    'query_spike_variant_by_region',
    'query_spike_variant_by_month',
    'query_spike_variant_by_sequence_feature',
    'query_spike_variant_by_growth_rate',
    'query_spike_variant_by_prevalence',
    'query_spike_variant_by_lineage_count',
    'query_spike_variant_by_total_isolates',
    'query_spike_variant_by_growth_rate_range',
    'query_spike_variant_by_prevalence_range',
    'query_spike_variant_by_lineage_count_range',
    'query_spike_variant_by_total_isolates_range',
    'query_spike_variant_by_date_range',
    'query_spike_variant_by_modified_date_range',
    'query_spike_variant_by_keyword',
    'query_spike_variant_all',
    
    # Strain functions
    'query_strain_by_id',
    'query_strain_by_filters',
    'query_strain_by_collection_date',
    'query_strain_by_collection_year',
    'query_strain_by_family',
    'query_strain_by_genus',
    'query_strain_by_species',
    'query_strain_by_strain',
    'query_strain_by_subtype',
    'query_strain_by_taxon_id',
    'query_strain_by_geographic_group',
    'query_strain_by_isolation_country',
    'query_strain_by_host_common_name',
    'query_strain_by_host_group',
    'query_strain_by_host_name',
    'query_strain_by_lab_host',
    'query_strain_by_owner',
    'query_strain_by_status',
    'query_strain_by_public',
    'query_strain_by_collection_year_range',
    'query_strain_by_date_inserted_range',
    'query_strain_by_date_modified_range',
    'query_strain_by_h_type_range',
    'query_strain_by_n_type_range',
    'query_strain_by_segment_count_range',
    'query_strain_by_taxon_id_range',
    'query_strain_by_keyword',
    'query_strain_all',
    
    # Structured assertion functions
    'query_structured_assertion_by_id',
    'query_structured_assertion_by_filters',
    'query_structured_assertion_by_comment',
    'query_structured_assertion_by_evidence_code',
    'query_structured_assertion_by_feature_id',
    'query_structured_assertion_by_owner',
    'query_structured_assertion_by_patric_id',
    'query_structured_assertion_by_pmid',
    'query_structured_assertion_by_property',
    'query_structured_assertion_by_public_status',
    'query_structured_assertion_by_refseq_locus_tag',
    'query_structured_assertion_by_score',
    'query_structured_assertion_by_source',
    'query_structured_assertion_by_value',
    'query_structured_assertion_by_user_read',
    'query_structured_assertion_by_user_write',
    'query_structured_assertion_by_version',
    'query_structured_assertion_by_date_inserted_range',
    'query_structured_assertion_by_date_modified_range',
    'query_structured_assertion_by_keyword',
    'query_structured_assertion_all',
    
    # Subsystem reference functions
    'query_subsystem_ref_by_id',
    'query_subsystem_ref_by_filters',
    'query_subsystem_ref_by_class',
    'query_subsystem_ref_by_description',
    'query_subsystem_ref_by_role',
    'query_subsystem_ref_by_role_id',
    'query_subsystem_ref_by_subsystem_id',
    'query_subsystem_ref_by_subsystem_name',
    'query_subsystem_ref_by_superclass',
    'query_subsystem_ref_by_date_inserted_range',
    'query_subsystem_ref_by_date_modified_range',
    'query_subsystem_ref_by_keyword',
    'query_subsystem_ref_all',
    
    # Subsystem functions
    'query_subsystem_by_id',
    'query_subsystem_by_filters',
    'query_subsystem_by_active',
    'query_subsystem_by_class',
    'query_subsystem_by_feature_id',
    'query_subsystem_by_gene',
    'query_subsystem_by_genome_id',
    'query_subsystem_by_genome_name',
    'query_subsystem_by_owner',
    'query_subsystem_by_patric_id',
    'query_subsystem_by_product',
    'query_subsystem_by_public_status',
    'query_subsystem_by_refseq_locus_tag',
    'query_subsystem_by_role_id',
    'query_subsystem_by_role_name',
    'query_subsystem_by_subclass',
    'query_subsystem_by_subsystem_id',
    'query_subsystem_by_subsystem_name',
    'query_subsystem_by_superclass',
    'query_subsystem_by_taxon_id',
    'query_subsystem_by_user_read',
    'query_subsystem_by_user_write',
    'query_subsystem_by_date_inserted_range',
    'query_subsystem_by_date_modified_range',
    'query_subsystem_by_keyword',
    'query_subsystem_all',
    
    # Surveillance functions
    'query_surveillance_by_id',
    'query_surveillance_by_filters',
    'query_surveillance_by_host_species',
    'query_surveillance_by_host_common_name',
    'query_surveillance_by_sample_identifier',
    'query_surveillance_by_sample_accession',
    'query_surveillance_by_collection_country',
    'query_surveillance_by_collection_city',
    'query_surveillance_by_collection_year',
    'query_surveillance_by_species',
    'query_surveillance_by_strain',
    'query_surveillance_by_subtype',
    'query_surveillance_by_pathogen_type',
    'query_surveillance_by_genome_id',
    'query_surveillance_by_disease_status',
    'query_surveillance_by_diagnosis',
    'query_surveillance_by_treatment',
    'query_surveillance_by_hospitalized',
    'query_surveillance_by_vaccination_type',
    'query_surveillance_by_exposure',
    'query_surveillance_by_pathogen_test_type',
    'query_surveillance_by_pathogen_test_result',
    'query_surveillance_by_collection_date_range',
    'query_surveillance_by_date_inserted_range',
    'query_surveillance_by_date_modified_range',
    'query_surveillance_by_keyword',
    'query_surveillance_all',
    
    # Taxonomy functions
    'query_taxonomy_by_id',
    'query_taxonomy_by_filters',
    'query_taxonomy_by_taxon_name',
    'query_taxonomy_by_taxon_rank',
    'query_taxonomy_by_lineage',
    'query_taxonomy_by_lineage_ids',
    'query_taxonomy_by_lineage_names',
    'query_taxonomy_by_parent_id',
    'query_taxonomy_by_division',
    'query_taxonomy_by_genetic_code',
    'query_taxonomy_by_genome_count',
    'query_taxonomy_by_core_families',
    'query_taxonomy_by_cds_mean',
    'query_taxonomy_by_genome_length_mean',
    'query_taxonomy_by_cds_mean_range',
    'query_taxonomy_by_core_families_range',
    'query_taxonomy_by_genetic_code_range',
    'query_taxonomy_by_genome_count_range',
    'query_taxonomy_by_genome_length_mean_range',
    'query_taxonomy_by_parent_id_range',
    'query_taxonomy_by_keyword',
    'query_taxonomy_all'

    # Bioset result functions
    'query_bioset_result_by_id',
    'query_bioset_result_by_filters',
    'query_bioset_result_by_bioset_id',
    'query_bioset_result_by_bioset_name',
    'query_bioset_result_by_bioset_description',
    'query_bioset_result_by_bioset_type',
    'query_bioset_result_by_entity_id',
    'query_bioset_result_by_entity_name',
    'query_bioset_result_by_entity_type',
    'query_bioset_result_by_exp_id',
    'query_bioset_result_by_exp_name',
    'query_bioset_result_by_exp_title',
    'query_bioset_result_by_exp_type',
    'query_bioset_result_by_feature_id',
    'query_bioset_result_by_gene',
    'query_bioset_result_by_gene_id',
    'query_bioset_result_by_genome_id',
    'query_bioset_result_by_locus_tag',
    'query_bioset_result_by_organism',
    'query_bioset_result_by_patric_id',
    'query_bioset_result_by_product',
    'query_bioset_result_by_protein_id',
    'query_bioset_result_by_result_type',
    'query_bioset_result_by_strain',
    'query_bioset_result_by_taxon_id',
    'query_bioset_result_by_uniprot_id',
    'query_bioset_result_by_other_id',
    'query_bioset_result_by_treatment_name',
    'query_bioset_result_by_treatment_type',
    'query_bioset_result_by_treatment_amount',
    'query_bioset_result_by_treatment_duration',
    'query_bioset_result_by_counts_range',
    'query_bioset_result_by_fpkm_range',
    'query_bioset_result_by_log2_fc_range',
    'query_bioset_result_by_p_value_range',
    'query_bioset_result_by_tpm_range',
    'query_bioset_result_by_other_value_range',
    'query_bioset_result_by_z_score_range',
    'query_bioset_result_by_version',
    'query_bioset_result_by_date_inserted_range',
    'query_bioset_result_by_date_modified_range',
    'query_bioset_result_by_keyword',
    'query_bioset_result_all',
]
